---
title: "cartographie_site_observation"
format: html
editor: visual
---

## cartographie de la reserve....

```{r}
library(leaflet)
library(sf)
library(RColorBrewer) 
library(dplyr)
library(readr)

#carte de la region : 
clc12 <- st_read("CLC_RLRMP_RGF_SHP/CLC12/CLC12_RLRMP_RGF.shp")


#zone qui nous interesse : bagnas 
bagnas_bbox <- st_as_sfc(st_bbox(c(
  xmin = 3.47,
  xmax = 3.58,
  ymin = 43.36,
  ymax = 43.43
), crs = 4326))

# Reprojeter la couche CLC en WGS84 si nécessaire
clc12_wgs <- st_transform(clc12, 4326)

# Découper
clc12_bagnas <- st_intersection(clc12_wgs, bagnas_bbox)


process_data <- read_csv("data/data_process/process_data.csv")

sites_sf <- st_as_sf(process_data, coords = c("x_centroid_4326", "y_centroid_4326"), crs = 4326)

```

## .... avec les points d'observation des oiseaux

carte interactive, on peut zoomer et cliquer sur les points pour avoir les noms d'espèces

```{r}

leaflet() %>%
  addTiles() %>%     # fond OSM
  addPolygons(
    data = clc12_bagnas,
    fillColor = "green",
    color = "darkgreen",
    weight = 1,
    fillOpacity = 0.4,
    popup = ~as.character(CODE_12)   # nom de l'attribut habitat CLC
  ) %>%
  addCircleMarkers(
    data =sites_sf,
    radius = 5,
    color = "red",
    fillOpacity = 0.9,
    popup = ~nom_vernaculaire
  ) %>%
  setView(lng = 3.3, lat = 43.6, zoom = 9)


```

## .... avec les les sites d'observation (protocole ou non?) des oiseaux

carte interactive, on peut zoomer et cliquer sur les points pour avoir les noms d'espèces

```{r}
leaflet() %>%
  addTiles() %>%     # fond OSM
  addPolygons(
    data = clc12_bagnas,
    fillColor = "green",
    color = "darkgreen",
    weight = 1,
    fillOpacity = 0.4,
    popup = ~as.character(CODE_12)   # nom de l'attribut habitat CLC
  ) %>%
  addCircleMarkers(
    data =sites_sf,
    radius = 5,
    color = "purple",
    fillOpacity = 0.9,
    popup = ~nom_lieu
  ) %>%
  setView(lng = 3.3, lat = 43.6, zoom = 9)


```
