<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Analyse des observations de Blongios nain (Ixobrychus minutus) dans la Reserve Naturelle du Bagnas</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="clean_blongios_files/libs/clipboard/clipboard.min.js"></script>
<script src="clean_blongios_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="clean_blongios_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="clean_blongios_files/libs/quarto-html/popper.min.js"></script>
<script src="clean_blongios_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="clean_blongios_files/libs/quarto-html/anchor.min.js"></script>
<link href="clean_blongios_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="clean_blongios_files/libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="clean_blongios_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="clean_blongios_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="clean_blongios_files/libs/bootstrap/bootstrap-bb462d781dde1847d9e3ccf7736099dd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<link href="clean_blongios_files/libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="clean_blongios_files/libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<script src="clean_blongios_files/libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>

<link href="clean_blongios_files/libs/leaflet-1.3.1/leaflet.css" rel="stylesheet">

<script src="clean_blongios_files/libs/leaflet-1.3.1/leaflet.js"></script>

<link href="clean_blongios_files/libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet">

<script src="clean_blongios_files/libs/proj4-2.6.2/proj4.min.js"></script>

<script src="clean_blongios_files/libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>

<link href="clean_blongios_files/libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet">

<script src="clean_blongios_files/libs/leaflet-binding-2.2.3/leaflet.js"></script>



<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analyse des observations de Blongios nain (Ixobrychus minutus) dans la Reserve Naturelle du Bagnas</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<div class="cell">
<style type="text/css">

body {
    text-align: justify}
    
</style>
</div>
<section id="introduction" class="level1">
<h1>1. Introduction</h1>
<p>Le Blongios nain (Ixobrychus minutus) est une espèce emblématique des zones humides, inféodée aux roselières inondées, aux berges de lacs et de cours d’eau ainsi qu’aux marais, qui lui fournissent à la fois des ressources alimentaires et des sites favorables à la nidification. Particulièrement discret, il demeure le plus souvent dissimulé au sein de la végétation, ce qui rend son observation difficile. Il s’agit d’une espèce migratrice, quittant les sites de reproduction européens à la fin de l’été pour hiverner principalement en Afrique subsaharienne.</p>
<p>L’Inventaire national du patrimoine naturel réalisé entre 2013 et 2015, indique que l’espèce est présente dans une cinquantaine de départements de France métropolitaine, notamment dans le nord du territoire (Hauts-de-France, Île-de-France), l’est (Grand Est, Auvergne-Rhône-Alpes), les départements littoraux du sud le long de la Méditerranée, ainsi que dans quelques départements du centre du pays. Toutefois, un déclin des populations est observé depuis les années 1970, principalement lié à la raréfaction et à la dégradation de ses habitats de reproduction. En conséquence, le Blongios nain est classé « En danger » (EN) sur la Liste rouge nationale, tandis qu’il est considéré en « Préoccupation mineure » (LC) à l’échelle européenne. Dans ce contexte, la réserve naturelle du Bagnas a exprimé le besoin de disposer d’une analyse approfondie des données d’observation du Blongios nain collectées sur le site entre 1990 et 2021.</p>
<p>L’objectif est, dans un premier temps, de comparer les données opportunistes à celles issues de protocoles standardisés de suivi — notamment les points d’écoute visant la détection des mâles chanteurs — afin d’évaluer l’efficacité et la pertinence des différents dispositifs de suivi. Dans un second temps, il s’agit de caractériser la structure spatio-temporelle de la présence du Blongios nain au sein de la réserve. Nous nous sommes ainsi interrogés sur la structure de l’effort de prospection au cours du temps, tant à l’échelle annuelle que journalière, ainsi que sur les facteurs influençant la détection de l’espèce lors des prospections, en lien avec sa phénologie et les modalités d’échantillonnage.</p>
</section>
<section id="analyses" class="level1">
<h1>3. Analyses</h1>
<section id="analyses-exploratoires" class="level2">
<h2 class="anchored" data-anchor-id="analyses-exploratoires">3.1 Analyses exploratoires</h2>
<section id="a-répartition-temporelle-des-observations-de-blongios-nain-depuis-1990" class="level3">
<h3 class="anchored" data-anchor-id="a-répartition-temporelle-des-observations-de-blongios-nain-depuis-1990">A) Répartition temporelle des observations de Blongios nain depuis 1990</h3>
<p>En premier lieu, nous voulions visualiser l’absence et la présence du Blongios nain sur toute la période d’étude. Pour cela, nous avons créé une grille années X semaines qui montre toutes les sorties avec et sans observation d’individus. Les cases du graphiques sont colorées de manière à différentier (i) les semaines avec observation d’un Blongios lors d’un protocole standardisé, (ii) les semaines avec observation opportuniste d’un Blongios, (iii) les semaines avec à la fois des observations opportuniste et par protocole standardisé, et (iiii) les semaines sans observation d’un Blongios.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Premièrement, on observe que l’ensemble des observations est concentré approximativement entre les semaines 16 et 35 (printemps–été), ce qui correspond bien à la période de présence du Blongios nain sur le littoral méditerranéen français. Le protocole de suivi standardisé a débuté en 2014, avec plusieurs passages réalisés tous les deux ans environ (entre 3 et 8 passages selon les années). Enfin, les résultats suggèrent une diminution de la présence du Blongios nain sur la réserve au cours du temps. En effet, le nombre total de semaines avec au moins une observation semble décroître, avec seulement deux semaines de présence détectée en 2024 contre onze en 2004. Cette tendance pourrait indiquer soit un déclin de la population globale, soit une diminution de l’attractivité écologique du site du Bagnas pour la population nicheuse.</p>
</section>
<section id="b-répartition-spatiale-des-observations-de-blongios-nain-issues-du-protocole-standardisé-de-suivi" class="level3">
<h3 class="anchored" data-anchor-id="b-répartition-spatiale-des-observations-de-blongios-nain-issues-du-protocole-standardisé-de-suivi">B) Répartition spatiale des observations de Blongios nain issues du protocole standardisé de suivi</h3>
<p>Ensuite, nous voulions visualiser la répartition spatiale des observations de Blongios nain issues du protocole standardisé de suivi. Pour cela, nous avons créé une carte avec des cercles dont la taille est proportionnelle au nombre total d’individus entendus/vus sur chaque site d’écoute depuis le début du protocole en 2014.</p>
<div class="cell">
<div class="cell-output-display">
<div class="leaflet html-widget html-fill-item" id="htmlwidget-8ac4acb3b120e4970f5d" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-8ac4acb3b120e4970f5d">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"addTiles","args":["https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",null,null,{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"attribution":"&copy; <a href=\"https://openstreetmap.org/copyright/\">OpenStreetMap<\/a>,  <a href=\"https://opendatacommons.org/licenses/odbl/\">ODbL<\/a>"}]},{"method":"addCircleMarkers","args":[[43.329853,43.322337,43.317739,43.314765,43.317255,43.320424,43.32293,43.331375,43.327324],[3.524423,3.524187,3.519831,3.510314,3.503888,3.509005,3.503405,3.515507,3.510068],[5,2,2,6,12,6,0,1,3],null,null,{"interactive":true,"className":"","stroke":true,"color":"red","weight":5,"opacity":0.5,"fill":true,"fillColor":"red","fillOpacity":0.9},null,null,["ButorTalèveBlongios-1, Blongios entendus :5","ButorTalèveBlongios-2, Blongios entendus :2","ButorTalèveBlongios-3, Blongios entendus :2","ButorTalèveBlongios-4, Blongios entendus :6","ButorTalèveBlongios-5, Blongios entendus :12","ButorTalèveBlongios-6, Blongios entendus :6","ButorTalèveBlongios-7, Blongios entendus :0","ButorTalèveBlongios-8, Blongios entendus :1","ButorTalèveBlongios-9, Blongios entendus :3"],null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]}],"limits":{"lat":[43.314765,43.331375],"lng":[3.503405,3.524423]},"setView":[[43.31,3.51],13,[]]},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>Sur cette carte on peut voir que certains sites semblent plus propice à l’observation d’individus de Blongios nain que d’autres. Notamment les sites n°5 et 6 semblent être les plus favorables à l’observation de cette espèce.</p>
</section>
<section id="c-effort-déchantillonnage-journalier-et-répartition-temporelle-journalière-des-observations-protocolées-de-blongios-nain" class="level3">
<h3 class="anchored" data-anchor-id="c-effort-déchantillonnage-journalier-et-répartition-temporelle-journalière-des-observations-protocolées-de-blongios-nain">C) Effort d’échantillonnage journalier et répartition temporelle journalière des observations protocolées de Blongios nain</h3>
<p>Ici, nous voulions comprendre à quel moment de la journée était réalisé le protocole, et quelles étaient les horaires qui permettaient une meilleure détection de l’espèce. Pour cela, nous avons réalisé un graphique qui représente l’effort d’échantillonnage ainsi que le nombre d’obervations cumulés au cours du protocole blongios pour chaque heure de la journée de 2014 à 2025. L’effort d’échantillonnage est représenté par la somme des sorties effectuées.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Ici, on observe que les sorties protocolées sont majoritairement réalisées entre 6 h et 7 h du matin ainsi qu’entre 20 h et 21 h, ce qui correspond aux plages horaires du protocole standardisé et aux périodes d’activité maximale du Blongios nain. Ces créneaux apparaissent pertinents, puisque c’est durant ces périodes que l’espèce est le plus fréquemment détectée</p>
</section>
<section id="d-effort-déchantillonnage-journalier-et-répartition-temporelle-journalière-des-observations-opportunistes-de-blongios-nain" class="level3">
<h3 class="anchored" data-anchor-id="d-effort-déchantillonnage-journalier-et-répartition-temporelle-journalière-des-observations-opportunistes-de-blongios-nain">D) Effort d’échantillonnage journalier et répartition temporelle journalière des observations opportunistes de Blongios nain</h3>
<p>Similairement, ici nous voulions comprendre à quel moment de la journée était faites les sorties hors protocole standardisé, et quelles étaient les horaires qui permettaient une meilleure détection de l’espèce sur ce type de données. Pour cela, nous avons réalisé un graphique qui représente le nombre d’obervations hors protocole cumulés pour chaque heure de la journée de 1997 à 2023. Il est important de préciser que les sorties hors protocole où l’heure d’observation est identifiée sont très rares (n=46), et correspondent en majorité à des données produites lors d’autres protocoles non dédiés à cette espèce.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>On remarque que hors protocole standardisé, le Blonios nain est essentiellement entre 6 et 11h du matin et entre 19 et 21h du soir, ce qui correspond bien à son pic d’activité (aube et crépuscule), et au horaires de prospections choisies pour le protocole dédié au Blongios nain.</p>
</section>
</section>
<section id="modèles-statistiques" class="level2">
<h2 class="anchored" data-anchor-id="modèles-statistiques">3.2. Modèles statistiques</h2>
<p>Maintenant que nous avons exploré les données, nous avons construit différent modèles statistiques pour voir si :</p>
<ul>
<li><p>il y a des tendances temporelles (intra- et inter- annuelles) significatives dans la présence et l’abondance du Blongios nain dans la réserve</p></li>
<li><p>il y a des différences spatiales (entre sites d’écoute) significatives dans la présence et l’abondance du Blongios nain dans la réserve</p></li>
<li><p>quelles variables environnementales (climatiques et hydrologiques) influencent la présence et l’abondance du Blongios nain</p></li>
</ul>
<p>Pour les analyses de présence et d’abondance, nous utilisons uniquement les données d’observation du blongios provenant des observations protocolées. Ce jeu de données sera nommé <strong>Protocole_SuiviBlongios</strong></p>
<section id="a-modèles-de-présenceabsence-du-blongios-nain" class="level3">
<h3 class="anchored" data-anchor-id="a-modèles-de-présenceabsence-du-blongios-nain">A) Modèles de présence/absence du Blongios Nain</h3>
<p>En premier lieu, nous réalisons un modèle pour essayer d’expliquer l’absence/présence du Blongios nain sur les 10 années de suivi protocolé. Pour cela nous utilisons la variable Occurence qui notifie la présence ou l’absence d’une observation de Blongios à chaque sortie.</p>
<p>Nous admettons que le modèle de base comprend uniquement les variables temporelles (année, jour julien) et spatiales (site d’écoute). Ensuite, nous comparons ce modèle de base à un modèle complet intégrant les variables environnementales (climatiques et hydrologiques). Un test de corrélation entre les variables environnementales est réalisé au préalable pour éviter la colinéarité entre variables explicatives.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Occurence ~ annee + julian + I(julian^2) + nom_lieu, 
    family = binomial, data = Protocole_SuiviBlongios)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                    1.443e+02  1.255e+02   1.150    0.250
annee                         -7.688e-02  6.229e-02  -1.234    0.217
julian                         1.193e-01  1.390e-01   0.858    0.391
I(julian^2)                   -3.747e-04  4.018e-04  -0.933    0.351
nom_lieuButorTalèveBlongios-2 -9.997e-01  8.938e-01  -1.119    0.263
nom_lieuButorTalèveBlongios-3 -9.997e-01  8.938e-01  -1.119    0.263
nom_lieuButorTalèveBlongios-4  2.471e-01  6.873e-01   0.359    0.719
nom_lieuButorTalèveBlongios-5  9.076e-01  6.432e-01   1.411    0.158
nom_lieuButorTalèveBlongios-6 -2.077e-01  7.436e-01  -0.279    0.780
nom_lieuButorTalèveBlongios-7 -1.706e+01  1.261e+03  -0.014    0.989
nom_lieuButorTalèveBlongios-8 -1.739e+00  1.139e+00  -1.527    0.127
nom_lieuButorTalèveBlongios-9 -5.459e-01  7.963e-01  -0.685    0.493

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 191.60  on 237  degrees of freedom
Residual deviance: 164.23  on 226  degrees of freedom
AIC: 188.23

Number of Fisher Scoring iterations: 17</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Occurence ~ annee + julian + I(julian^2) + nom_lieu + 
    temp_moy_glissante_31j + pluie_moy_glissante_31j + pluie_moy_glissante_7j + 
    pluie_1h + AssecT_1 + Profondeur, family = binomial, data = Protocole_SuiviBlongios)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                    1.263e+02  2.360e+02   0.535    0.593
annee                         -7.240e-02  1.125e-01  -0.643    0.520
julian                         2.606e-01  2.931e-01   0.889    0.374
I(julian^2)                   -7.337e-04  7.324e-04  -1.002    0.316
nom_lieuButorTalèveBlongios-2 -1.007e+00  9.056e-01  -1.112    0.266
nom_lieuButorTalèveBlongios-3 -1.007e+00  9.056e-01  -1.112    0.266
nom_lieuButorTalèveBlongios-4 -1.946e-01  7.580e-01  -0.257    0.797
nom_lieuButorTalèveBlongios-5  9.480e-01  6.612e-01   1.434    0.152
nom_lieuButorTalèveBlongios-6 -1.946e-01  7.580e-01  -0.257    0.797
nom_lieuButorTalèveBlongios-7 -1.710e+01  1.266e+03  -0.014    0.989
nom_lieuButorTalèveBlongios-8 -1.757e+00  1.148e+00  -1.530    0.126
nom_lieuButorTalèveBlongios-9 -5.432e-01  8.096e-01  -0.671    0.502
temp_moy_glissante_31j        -1.600e-01  4.025e-01  -0.398    0.691
pluie_moy_glissante_31j       -1.181e+01  1.792e+01  -0.659    0.510
pluie_moy_glissante_7j        -6.119e+00  7.796e+00  -0.785    0.433
pluie_1h                       3.863e+00  1.975e+01   0.196    0.845
AssecT_1total                  7.099e-01  9.642e-01   0.736    0.462
Profondeur                    -1.461e+00  3.314e+00  -0.441    0.659

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 181.29  on 227  degrees of freedom
Residual deviance: 150.82  on 210  degrees of freedom
  (10 observations effacées parce que manquantes)
AIC: 186.82

Number of Fisher Scoring iterations: 17</code></pre>
</div>
</div>
<p>Nous obervons que les trois variables de température sont fortement corrélées entre elles (R&gt;0.8), donc nous conservons que la variable de température moyénnée à 7 jours avant la date du suivi. Concernant les précipitations, nous gardons les trois variables (du jour J, moyenne sur 7 et 31 jours).</p>
<p>La variable temporelle interannuelle (année) et intraannuelle (jours julian) n’ont pas d’effet significatif sur la présence de l’espèce, ce qui signifie que la probabilité d’occurrence de l’espèce ne varie pas significativement entre 2014 et 2024 (β = -0.072 ± 0.113, p = 0.52), ni durant la durée du protocole (β = 0.261 ± 0.293, p = 0.374. De même, il n’y a aucun site qui montre une meilleure présence de Blongios sur la réserve, et aucune variables environnementales qui explique significativement l’occurence du Blongios nain.</p>
<p>Graphiques (je pense ne pas mettre)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-13-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b-modèles-dabondance-du-blongios-nain" class="level3">
<h3 class="anchored" data-anchor-id="b-modèles-dabondance-du-blongios-nain">B) Modèles d’abondance du Blongios nain</h3>
<p>Ensuite, nous avons refait les mêmes modèles avec les même variables explicatives, mais avec la variable nombre_min (Abondance). Cela nous à permis de vérifier s’il y avait (i) des tendances temporelles dans les populations de Blongios de la réserve, (ii) des sites avec plus d’individus observés ou (iii) des variables environnementales qui pouvaient influencer le nombre d’individus recensé lors du suivi.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = nombre_min ~ annee + julian + I(julian^2) + nom_lieu, 
    family = poisson, data = Protocole_SuiviBlongios)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                    5.338e+01  1.032e+02   0.517    0.605
annee                         -3.205e-02  5.108e-02  -0.628    0.530
julian                         1.238e-01  1.224e-01   1.011    0.312
I(julian^2)                   -3.911e-04  3.567e-04  -1.097    0.273
nom_lieuButorTalèveBlongios-2 -8.646e-01  8.367e-01  -1.033    0.301
nom_lieuButorTalèveBlongios-3 -8.646e-01  8.367e-01  -1.033    0.301
nom_lieuButorTalèveBlongios-4  1.942e-01  6.059e-01   0.321    0.749
nom_lieuButorTalèveBlongios-5  8.307e-01  5.324e-01   1.560    0.119
nom_lieuButorTalèveBlongios-6  2.340e-01  6.056e-01   0.386    0.699
nom_lieuButorTalèveBlongios-7 -1.656e+01  1.099e+03  -0.015    0.988
nom_lieuButorTalèveBlongios-8 -1.558e+00  1.095e+00  -1.422    0.155
nom_lieuButorTalèveBlongios-9 -4.592e-01  7.304e-01  -0.629    0.530

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 149.88  on 237  degrees of freedom
Residual deviance: 120.97  on 226  degrees of freedom
AIC: 213.19

Number of Fisher Scoring iterations: 16</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = nombre_min ~ annee + julian + I(julian^2) + nom_lieu + 
    temp_moy_glissante_31j + pluie_moy_glissante_31j + pluie_moy_glissante_7j + 
    pluie_1h + AssecT_1 + Profondeur, family = poisson, data = Protocole_SuiviBlongios)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)
(Intercept)                   -4.498e+01  1.827e+02  -0.246    0.806
annee                          1.341e-02  8.710e-02   0.154    0.878
julian                         2.304e-01  2.382e-01   0.967    0.333
I(julian^2)                   -6.847e-04  6.020e-04  -1.137    0.255
nom_lieuButorTalèveBlongios-2 -8.503e-01  8.369e-01  -1.016    0.310
nom_lieuButorTalèveBlongios-3 -8.503e-01  8.369e-01  -1.016    0.310
nom_lieuButorTalèveBlongios-4 -1.571e-01  6.711e-01  -0.234    0.815
nom_lieuButorTalèveBlongios-5  8.228e-01  5.326e-01   1.545    0.122
nom_lieuButorTalèveBlongios-6  2.483e-01  6.059e-01   0.410    0.682
nom_lieuButorTalèveBlongios-7 -1.749e+01  1.757e+03  -0.010    0.992
nom_lieuButorTalèveBlongios-8 -1.543e+00  1.096e+00  -1.409    0.159
nom_lieuButorTalèveBlongios-9 -4.448e-01  7.306e-01  -0.609    0.543
temp_moy_glissante_31j        -7.976e-02  3.260e-01  -0.245    0.807
pluie_moy_glissante_31j       -1.107e+01  1.487e+01  -0.744    0.457
pluie_moy_glissante_7j        -6.602e+00  7.180e+00  -0.919    0.358
pluie_1h                       8.811e+00  1.768e+01   0.498    0.618
AssecT_1total                 -1.487e-02  7.824e-01  -0.019    0.985
Profondeur                    -1.372e+00  2.640e+00  -0.520    0.603

(Dispersion parameter for poisson family taken to be 1)

    Null deviance: 143.32  on 227  degrees of freedom
Residual deviance: 109.66  on 210  degrees of freedom
  (10 observations effacées parce que manquantes)
AIC: 209.88

Number of Fisher Scoring iterations: 17</code></pre>
</div>
</div>
<p>La variable temporelle interannuelle (année) et intraannuelle (jours julian) n’ont pas d’effet significatif sur l’abondance de l’espèce, ce qui signifie que le nombre d’individus contacté lors des suivis protocolés de l’espèce ne varie pas significativement entre 2014 et 2024 (β = 0.013 ± 0.087, p = 0.878), ni durant la durée du protocole (β = 0.23 ± 0.238, p = 0.333. De même, il n’y a aucun site de la réserve qui montre un nombre de Blongios observé plus important, et aucune des variables environnementales qui expliquent significativement les variations d’abondance du Blongios nain.</p>
<p>Graphiques (à ne pas mettre je pense)</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-5.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-6.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="clean_blongios_files/figure-html/unnamed-chunk-15-7.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>