
## R code For Geographical coordinates cleaning and processing
```{r}
library(ggplot2)
library(dplyr)
getwd()

# Import data
options(encoding = "latin1")
raw_data <- read.csv("data/raw/synthese_observations_oiseaux.csv", sep = ";")

# Convert raw_data into processed_data

# select necessary columns
process_data <- raw_data %>% select(id_synthese, date_debut, date_fin,heure_debut, heure_fin, nom_vernaculaire, nombre_min,observateurs,determinateur,x_centroid_4326, y_centroid_4326,nom_lieu,champs_additionnels)

# write new file
write.csv(process_data, file = "C:/Users/rapha/Desktop/MASTER 2 RAINET/UE Projet entreprise/oiseaux_bagnas/data/processed/process_data.csv", row.names = FALSE)

bird_data <- read.csv("data/processed/process_data.csv", sep = ",")

bird_data$nom_lieu <- as.factor(bird_data$nom_lieu)
levels(bird_data$nom_lieu)

coord_summary <- bird_data %>%
  group_by(x_centroid_4326, y_centroid_4326) %>%                 
  summarise(
    n_sites = n_distinct(nom_lieu),                              
    site_names = paste(unique(nom_lieu), collapse = ", "),       
    coord_unique = n_sites == 1                                   
  ) %>%
  ungroup() %>%
  arrange(desc(n_sites)) 


bird_data <- bird_data %>%
  mutate(nom_lieu = ifelse(is.na(nom_lieu) | nom_lieu == "",
                           paste0("unnamedSite", row_number()), 
                           as.character(nom_lieu)))

bird_data <- bird_data %>%
  mutate(nom_lieu = as.character(nom_lieu)) %>%
  mutate(nom_lieu = ifelse(nom_lieu %in% c("Portiragnes", "RNNbagnas", "Bessan"),
                           "SudEtangBagnas",
                           nom_lieu)) %>%
  mutate(nom_lieu = as.factor(nom_lieu))

bird_data$nom_lieu <- as.factor(bird_data$nom_lieu)

levels(bird_data$nom_lieu)

coord_summary <- bird_data %>%
  group_by(x_centroid_4326, y_centroid_4326) %>%                 
  summarise(
    n_sites = n_distinct(nom_lieu),                              
    site_names = paste(unique(nom_lieu), collapse = ", "),      
    coord_unique = n_sites == 1                                  
  ) %>%
  ungroup() %>%
  arrange(desc(n_sites))



```


## R code for Binomial GLM
```{r}

### Importe les packages
library(ggplot2)
library(dplyr)
library(lubridate)


### Importe les données
BirdData <- read.csv("data/pro/process_protocole.csv", sep = ",")
EnvironmentalData <- read.csv("data/pro/environnement_daily.csv", sep = ",")
HydrologicData <- read.csv("data/raw/DataHydro.csv", sep = ";")
HydrologicDataGrandBagnas <- HydrologicData %>%
  select(Station, Date.Releve, Heure, Salinite, Temperature, Niveau.Ngf, Niveau.Relatif)%>%
  mutate(Profondeur = (Niveau.Ngf+0.27),
         Date.Releve = as.Date(Date.Releve, format = "%d/%m/%Y"),
         Annee = as.integer(format(Date.Releve, "%Y")),
         Mois = format(Date.Releve, "%m"),
         Jour = yday(Date.Releve))%>%
  filter(Station == "Etangs du Grand Bagnas - TB5 centre",
         Annee > 2013)

### Calcule la profondeur et l'altitude moyenne (de l'eau) mensuelle
Hydro_moyenne <- HydrologicDataGrandBagnas %>%
  group_by(Annee, Mois) %>%
  summarise(
    ProfondeurMoyenne = mean(Profondeur, na.rm = TRUE),
    AltitudeMoyenne = mean(Niveau.Ngf, na.rm = TRUE),
    .groups = "drop"    # <--- important pour éviter des regroupements inutiles
  )


### Code une variable Assec (mois par mois) et AssecT (niveau le plus extreme de l'année) 
Hydro_moyenne <- Hydro_moyenne %>%
  mutate(
    Assec = case_when(
      is.na(ProfondeurMoyenne) ~ "total",
      ProfondeurMoyenne < 0.2  ~ "partiel",
      TRUE                     ~ "non"),
    Assec_score = case_when(
      Assec == "non"     ~ 1,
      Assec == "partiel" ~ 2,
      Assec == "total"   ~ 3)) %>%
  group_by(Annee) %>%
  mutate(
    AssecT = case_when(
      max(Assec_score, na.rm = TRUE) == 3 ~ "total",
      max(Assec_score, na.rm = TRUE) == 2 ~ "partiel",
      TRUE                                ~ "non")) %>%
  ungroup() %>%
  select(-Assec_score)

### Crée une variable AssecT_1 (AssecT de l'année précédente)
Assec_annuel <- Hydro_moyenne %>%
  distinct(Annee, AssecT) %>%
  bind_rows(tibble(Annee = 2014, AssecT = "non")) %>%
  filter(Annee != 2026) %>%                             
  arrange(Annee) %>%
  mutate(
    AssecT_1 = lag(AssecT),
    AssecT_1 = if_else(Annee == 2014, "non", AssecT_1))


Assec_annuel <- Assec_annuel %>%
  group_by(Annee) %>%
  slice(1) %>%   # garde la première ligne si doublons
  ungroup()
### Intègre AssecT_1 dans Hydro_moyenne
Hydro_moyenne <- Hydro_moyenne %>%
  left_join(
    Assec_annuel %>% select(Annee, AssecT_1),
    by = "Annee")

Hydro_moyenne <- Hydro_moyenne[-c(4,5,6)]

Hydro_moyenne <- Hydro_moyenne %>%
  mutate(ProfondeurMoyenne = if_else(is.na(ProfondeurMoyenne), 0, ProfondeurMoyenne))

```

